### ISSUE TITLE
Add SASL Mechanisms DH-Blowfish and DH-AES

### ISSUE THREAD

**Issue by kabaka** [Terminus-Project/Terminus-Bot#46]
Presently, we only support `plain` SASL authentication, which sends credentials base 64 encoded. DH-AES is the preferred method of authentication. DH-Blowfish should be included for legacy networks until DH-AES is more widely deployed.

**Comment by akaritakai** [comment]
This issue should be closed since: Atheme dropped support for it (https://github.com/atheme/atheme/commit/15f6d84), the mechanisms are non-standard, and they provide no benefit over PLAIN authentication.
