### ISSUE TITLE
Fix automatic and manual reconnection

### ISSUE THREAD

**Issue by kabaka** [Terminus-Project/Terminus-Bot#50]
Presently, the bot fails to automatically reconnect in almost all circumstance. Manual reconnection (via the `reconnect` command) works *sometimes*.

The relevant code has not really been maintained or updated for a while and is full of mixed and confusing ideas. Rework the entire thing.

**Comment by kabaka** [comment]
@skyhighwings or someone ­— has this been an ongoing issue lately?

**Comment by Xe** [comment]
From what I have seen from the remaining terminus-bot instances that I know of, it works "fine enough". The main one I know about has been stable since `09-11-2015`.

**Comment by kabaka** [comment]
Closing since I haven't heard back in a while.
