### ISSUE TITLE
SSL overrides non-SSL connections

### ISSUE THREAD

**Issue by Theyoungster** [Terminus-Project/Terminus-Bot#82]
Earlier, I tried to connection to Rizon using an SSL connection, and irc.hypnoponies.net with a non-SSL connection. For some reason, I was unable to establish a connection with the hypnoponies IRC until I moved the Rizon connection to non-SSL.

**Comment by kabaka** [comment]
I don't see an easy path for this to happen in the code. I would attempt the connection as originally configured a second time.

If it fails again, set the `core.loglevel` option to DEBUG and provide us the logs of the connection failure, as well as the server configuration section of your config file (with any credentials masked or removed, as necessary).

**Comment by Theyoungster** [comment]
Well.
Interestingly, when I tried to reproduce it, it ended up working perfectly fine. Both connections worked as intended.

**Comment by Theyoungster** [comment]
Well.
Interestingly, when I tried to reproduce it, it ended up working perfectly fine. Both connections worked as intended.
